boun
zion08/goworker pull request #117
Opened 2021-11-17 08:50 UTC by jeongboun

project 추가
search 수정
헤더 추가
pay string 으로 변경

2021-11-17 08:57 UTC, zion08 requested changes
project_input.jsp에 프로젝트 유형이 pay로 지정되어있습니다. 확인 후 수정해주세요

2021-11-17 13:16 UTC, 2thumbz approved these changes
확인

2021-11-17 13:28 UTC, 2thumbz approved these changes
확인

2021-11-18 00:34 UTC, zion08 approved these changes
확인

2021-11-18 00:40 UTC, merged